FROM node:24-bullseye-slim
RUN npm install -g pnpm
RUN apt-get update && \
    apt-get install -y python3 make g++ git curl && \
    ln -sf python3 /usr/bin/python && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /app 
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install
COPY . .
RUN chown -R node:node /app
USER node
EXPOSE 3000
CMD ["pnpm", "run", "dev"]