import { z } from "zod";
import { globalRoleSchema } from "@/schemas/roles.schema";
import { queryParamsSchema } from "@/schemas/shared.schema";

export const socialAuthProviderSchema = z.enum([
  "google",
  "github",
  "linkedin",
]);
export type SocialAuthProviderType = z.infer<typeof socialAuthProviderSchema>;

// Base User Schema (matches SPECS.md User model)
export const userSchema = z.object({
  id: z.string(), // Primary key for the User record
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  primaryEmail: z.string().email(),
  passwordHash: z.string().optional(), // Only for password-based accounts
  globalRole: globalRoleSchema.default("student"),
  emails: z.array(
    z.object({
      emailAddress: z.string().email(),
      isVerified: z.boolean().default(false),
      verificationToken: z.string().optional(),
      verificationTokenExpiresAt: z.date().optional(),
      addedAt: z.date(),
    })
  ),
  socialIdentities: z.array(
    z.object({
      provider: socialAuthProviderSchema,
      providerUserId: z.string(),
      email: z.string().email().optional(),
      name: z.string().optional(),
      linkedAt: z.date(),
    })
  ),
  lastLoginAt: z.date().optional(),
  passwordLastChangedAt: z.date().optional(),
  isAccountLocked: z.boolean().default(false),
  failedLoginAttempts: z.number().default(0),
  accountLockedAt: z.date().optional(),
  accountLockedUntil: z.date().optional(),
  createdAt: z.date().optional(), // Set by DB/service, present on retrieved entities
  updatedAt: z.date().optional(), // Set by DB/service, present on retrieved entities
});

export type UserType = z.infer<typeof userSchema>;

// Email object schema (for embedded documents)
export const emailObjectSchema = z.object({
  emailAddress: z.string().email(),
  isVerified: z.boolean().default(false),
  verificationToken: z.string().optional(),
  verificationTokenExpiresAt: z.date().optional(),
  addedAt: z.date(),
});

export type EmailObjectType = z.infer<typeof emailObjectSchema>;

// Social identity schema (for embedded documents)
export const socialIdentityObjectSchema = z.object({
  provider: z.enum(["google", "github", "linkedin"]),
  providerUserId: z.string(),
  email: z.string().email().optional(),
  name: z.string().optional(),
  linkedAt: z.date(),
});

export type SocialIdentityObjectType = z.infer<
  typeof socialIdentityObjectSchema
>;

// Registration schema (for user registration)
export const registerUserSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8, "Password must be at least 8 characters"),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
});

export type RegisterUserType = z.infer<typeof registerUserSchema>;

// Create user schema (for repository layer)
export const createUserSchema = userSchema.omit({
  id: true, // Will be generated by the service/system
  createdAt: true, // Will be set by the service/database
  updatedAt: true, // Will be set by the service/database
});

export type CreateUserType = z.infer<typeof createUserSchema>;

// Update user schema (for profile updates)
export const updateUserSchema = z
  .object({
    firstName: z.string().optional(),
    lastName: z.string().optional(),
  })
  .partial();

export type UpdateUserType = z.infer<typeof updateUserSchema>;

// Login credentials schema
export const loginCredentialsSchema = z.object({
  email: z.string().email(),
  password: z.string().min(1, "Password is required"),
});

export type LoginCredentialsType = z.infer<typeof loginCredentialsSchema>;

// Change password schema
export const changePasswordSchema = z.object({
  currentPassword: z.string().min(1, "Current password is required"),
  newPassword: z.string().min(8, "New password must be at least 8 characters"),
});

export type ChangePasswordType = z.infer<typeof changePasswordSchema>;

// Add email schema
export const addEmailSchema = z.object({
  emailAddress: z.string().email(),
});

export type AddEmailType = z.infer<typeof addEmailSchema>;

// Set primary email schema
export const setPrimaryEmailSchema = z.object({
  emailAddress: z.string().email(),
});

export type SetPrimaryEmailType = z.infer<typeof setPrimaryEmailSchema>;

// Refresh token request schema
export const refreshTokenRequestSchema = z.object({
  refreshToken: z.string().min(1, "Refresh token is required"),
});

export type RefreshTokenRequestType = z.infer<typeof refreshTokenRequestSchema>;

// Email verification request schema
export const emailVerificationRequestSchema = z.object({
  token: z.string().min(1, "Verification token is required"),
});

export type EmailVerificationRequestType = z.infer<
  typeof emailVerificationRequestSchema
>;

// Resend verification request schema
export const resendVerificationRequestSchema = z.object({
  userId: z.string().min(1, "User ID is required"),
  emailAddress: z.string().email("Valid email address is required"),
});

export type ResendVerificationRequestType = z.infer<
  typeof resendVerificationRequestSchema
>;

// Delete account request schema
export const deleteAccountRequestSchema = z.object({
  password: z.string().min(1, "Password is required for account deletion"),
});

export type DeleteAccountRequestType = z.infer<
  typeof deleteAccountRequestSchema
>;

// Email address parameter schema
export const emailAddressParamSchema = z.object({
  emailAddress: z.string().email("Valid email address is required"),
});

export type EmailAddressParamType = z.infer<typeof emailAddressParamSchema>;

// Refresh token schema
export const refreshTokenSchema = z.object({
  id: z.string(), // Primary key for the RefreshToken record
  tokenHash: z.string(), // Hashed refresh token
  userId: z.string(), // References User.id
  userAgent: z.string().optional(),
  ipAddress: z.string().optional(),
  expiresAt: z.date(),
  isRevoked: z.boolean().default(false),
  createdAt: z.date().optional(), // Set by DB/service, present on retrieved entities
});

export type RefreshTokenType = z.infer<typeof refreshTokenSchema>;

// Create refresh token schema
export const createRefreshTokenSchema = refreshTokenSchema.omit({
  id: true,
  createdAt: true,
});

export type CreateRefreshTokenType = z.infer<typeof createRefreshTokenSchema>;

// Admin setting schema
export const adminSettingSchema = z.object({
  id: z.string(), // Primary key for the AdminSetting record
  key: z.string(), // e.g., "universityEmailPattern", "passwordPolicyMinLength"
  value: z.unknown(), // Mixed type for flexible configuration
  description: z.string().optional(),
  updatedAt: z.date().optional(), // Set by DB/service, present on retrieved entities
});

export type AdminSettingType = z.infer<typeof adminSettingSchema>;

// User ID type (for consistency with existing code)
export const userIdSchema = z.string();
export type UserIdType = z.infer<typeof userIdSchema>;

// Authenticated user context (for middleware)
export const authenticatedUserContextSchema = z.object({
  userId: userIdSchema, // References User.id
  globalRole: globalRoleSchema,
  primaryEmail: z.string().email(),
});

export type AuthenticatedUserContextType = z.infer<
  typeof authenticatedUserContextSchema
>;

// JWT payload schema
export const jwtPayloadSchema = z.object({
  userId: z.string(),
  email: z.string().email(),
  role: globalRoleSchema,
  iat: z.number(),
  exp: z.number(),
});

export type JWTPayloadType = z.infer<typeof jwtPayloadSchema>;

// Refresh JWT payload schema
export const refreshJWTPayloadSchema = z.object({
  userId: z.string(),
  type: z.literal("refresh"),
  iat: z.number(),
  exp: z.number(),
});

export type RefreshJWTPayloadType = z.infer<typeof refreshJWTPayloadSchema>;

// User-specific query parameters schema
export const userQueryParamsSchema = queryParamsSchema.extend({
  role: globalRoleSchema.optional(),
});

export type UserQueryParamsType = z.infer<typeof userQueryParamsSchema>;

export const adminRegisterUserSchema = registerUserSchema.extend({
  globalRole: globalRoleSchema.default("student"),
});
export type AdminRegisterUserType = z.infer<typeof adminRegisterUserSchema>;
